default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        description: Sorts import statements
        args:
          - --profile=black
          - --line-length=120

  - repo: https://github.com/myint/eradicate
    rev: v2.1.0
    hooks:
      - id: eradicate
        description: Eradicate removes unused commented code
        args:
          - --in-place

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        description: Pyupgrade replaces deprecated syntax with the newest syntax
        args:
          - --py310-plus

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --in-place

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        description: Black is an automatic Python code formatter. It ensures code readability and PEP8 compliance.
        args:
          - --line-length=120

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - pydantic
        args:
          - --strict
          - --ignore-missing-imports
          - --allow-untyped-decorators
          - --implicit-reexport

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        description: Flake8 is a command-line utility for enforcing style consistency across Python projects.
        additional_dependencies:
          - flake8-pep585
          - flake8-new-union-types
          - flake8-json
          - flake8-adjustable-complexity
          - flake8-annotations-coverage
          - flake8-builtins
          - flake8-cognitive-complexity
          - flake8-comprehensions
          - flake8-expression-complexity
          - flake8-functions
          - flake8-simplify
          - flake8-scream
          - pep8-naming
          - flake8-bugbear
          - flake8-print
          - flake8-use-pathlib
          - pylint
          - flake8-pylint
        args:
          - --count
          - --max-line-length=130
          - --exclude=*test*

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        description: Ensures no big files are commited
      - id: check-json
        description: Ensures valid JSON
      - id: check-yaml
        description: Ensures valid YAML
      - id: check-case-conflict
        description: Ensures there are no name conflicts in case insesnsitive systems
      - id: check-merge-conflict
        description: Ensures there are no merge conflict lines
      - id: detect-private-key
        description: Detects commited private keys
      - id: pretty-format-json
        description: Prettifies JSON
