name: Auto Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: get version
      id: get_version
      shell: bash
      run: |
        echo "::set-output name=name::$(poetry version)"
        echo "::set-output name=version::$(poetry version | cut -d " " -f 2)"

    - name: Upload assets to release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.get_version.outputs.name }}
        tag_name: ${{ steps.get_version.outputs.version }}
